services:
  colab-local-env:
    image: us-docker.pkg.dev/colab-images/public/runtime
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
