[project]
name = "iprofihack2025-phystech-cartography"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "albumentations==2.0.8",
    "boto3>=1.39.1",
    "botocore>=1.39.1",
    "faiss-cpu==1.7.4",
    "loguru==0.7.3",
    "numpy==1.26.4",
    "typer>=0.16.0",
]
